"""EWM reasoning trace: the serialized interleaving of reasoner-generated
segments and world-module observations.

This module is the *representation* at the heart of Einstein World Models
(Nwadike et al., 2606.26969). Two facts from the paper drive every design
choice here:

1. A trace T is built by appending segments (Eq. 1). Ordinary text segments
   (think / tool_call / answer) are generated by the reasoner. A
   <visual_rollout> is an *observation* returned by the world-module W.

2. For BOTH training objectives, returned-rollout tokens are masked from the
   loss: the indicator 1_it = 0 over rollout observations (Appendix A for SFT
   cross-entropy; Eq. 3 for the GRPO surrogate). The reasoner is never trained
   to *produce* the pixels W hands it -- only to decide when/how to query and
   how to use what comes back.

Tags follow the paper's §2.3 serialization (mirroring Search-R1 style tool
tags):
    <think>...</think>                language reasoning            (generated)
    <tool_call>{"name": "world_module", "query": q}</tool_call>     (generated)
    <visual_rollout>...</visual_rollout>   returned rollout observation (MASKED)
    <answer>...</answer>              final answer                  (generated)
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Iterable


class Kind(str, Enum):
    THINK = "think"
    TOOL_CALL = "tool_call"
    VISUAL_ROLLOUT = "visual_rollout"
    ANSWER = "answer"

    @property
    def generated(self) -> bool:
        """True if the reasoner produced this segment (contributes to the loss).

        Only VISUAL_ROLLOUT is a returned observation -> masked. Everything
        else is policy-generated. This single predicate is what both sft.py
        and grpo.py consult to build the token loss mask.
        """
        return self is not Kind.VISUAL_ROLLOUT


TAG = {
    Kind.THINK: ("<think>", "</think>"),
    Kind.TOOL_CALL: ("<tool_call>", "</tool_call>"),
    Kind.VISUAL_ROLLOUT: ("<visual_rollout>", "</visual_rollout>"),
    Kind.ANSWER: ("<answer>", "</answer>"),
}


@dataclass
class Segment:
    kind: Kind
    text: str
    # World-module bookkeeping for rollouts: frame paths, the query that
    # produced them, latency, etc. Kept out of the serialized token stream but
    # preserved in the inspectable bundle (the paper's whole point: rollouts as
    # *inspectable* hypotheses, §2.2).
    meta: dict[str, Any] = field(default_factory=dict)

    def render(self) -> str:
        open_t, close_t = TAG[self.kind]
        return f"{open_t}{self.text}{close_t}"


@dataclass
class Trace:
    """A (possibly partial) EWM trace. T_0 = x is stored in `problem`."""

    problem: str
    segments: list[Segment] = field(default_factory=list)

    # ---- construction (Eq. 1 trace update) --------------------------------
    def append(self, seg: Segment) -> "Trace":
        self.segments.append(seg)
        return self

    def think(self, text: str) -> "Trace":
        return self.append(Segment(Kind.THINK, text))

    def tool_call(self, query: str) -> "Trace":
        payload = json.dumps({"name": "world_module", "query": query})
        return self.append(Segment(Kind.TOOL_CALL, payload, meta={"query": query}))

    def visual_rollout(self, description: str, **meta: Any) -> "Trace":
        return self.append(Segment(Kind.VISUAL_ROLLOUT, description, meta=meta))

    def answer(self, text: str) -> "Trace":
        return self.append(Segment(Kind.ANSWER, text))

    # ---- inspection -------------------------------------------------------
    @property
    def n_world_calls(self) -> int:
        """M(T): number of world-module calls (used by the §2.4.1 penalty)."""
        return sum(1 for s in self.segments if s.kind is Kind.TOOL_CALL)

    @property
    def final_answer(self) -> str | None:
        for s in reversed(self.segments):
            if s.kind is Kind.ANSWER:
                return s.text.strip()
        return None

    def render(self) -> str:
        return self.problem + "".join(s.render() for s in self.segments)

    # ---- the loss mask (Appendix A / Eq. 3) -------------------------------
    def loss_mask(self, tokenizer) -> tuple[list[int], list[int]]:
        """Tokenize the full trace and return (token_ids, mask).

        mask[t] == 1 for reasoner-generated tokens (1_it = 1), 0 for tokens
        that are part of a returned <visual_rollout> observation. The problem
        prompt x is also masked (it is given, not generated). This is the exact
        quantity both training objectives sum over.

        Tokenizer-agnostic: works with any HF tokenizer exposing .encode().
        """
        ids: list[int] = []
        mask: list[int] = []

        def add(text: str, generated: bool) -> None:
            toks = tokenizer.encode(text, add_special_tokens=False)
            ids.extend(toks)
            mask.extend([1 if generated else 0] * len(toks))

        add(self.problem, generated=False)  # x is given
        for s in self.segments:
            add(s.render(), generated=s.kind.generated)
        return ids, mask

    def mask_spans(self) -> list[tuple[str, bool]]:
        """Tokenizer-free view of the mask: (text_span, is_generated) pairs.

        Lets tests and the smoke run verify masking without a tokenizer.
        """
        spans: list[tuple[str, bool]] = [(self.problem, False)]
        for s in self.segments:
            spans.append((s.render(), s.kind.generated))
        return spans


# --------------------------------------------------------------------------
# Parsing reasoner output back into segments + control signals for the loop.
# --------------------------------------------------------------------------

_TAG_RE = re.compile(
    r"<(think|tool_call|answer)>(.*?)</\1>", re.DOTALL
)


def parse_generated(text: str) -> list[Segment]:
    """Parse a reasoner's raw output into generated segments.

    The reasoner is never expected to emit <visual_rollout> itself -- that tag
    is injected by the loop after W returns. We tolerate stray prose outside
    tags by attaching it to a THINK segment so nothing is silently dropped.
    """
    segs: list[Segment] = []
    pos = 0
    for m in _TAG_RE.finditer(text):
        lead = text[pos:m.start()].strip()
        if lead:
            segs.append(Segment(Kind.THINK, lead))
        kind = Kind(m.group(1))
        body = m.group(2).strip()
        if kind is Kind.TOOL_CALL:
            segs.append(Segment(kind, body, meta={"query": _extract_query(body)}))
        else:
            segs.append(Segment(kind, body))
        pos = m.end()
    tail = text[pos:].strip()
    if tail and not segs:
        segs.append(Segment(Kind.THINK, tail))
    return segs


def _extract_query(tool_body: str) -> str | None:
    try:
        obj = json.loads(tool_body)
        return obj.get("query")
    except json.JSONDecodeError:
        # tolerate a bare query string inside the tags
        return tool_body.strip() or None


def next_control_segment(segs: Iterable[Segment]) -> Segment | None:
    """Return the first segment that changes control flow (tool_call/answer),
    or None if the chunk is pure thinking. Used by the inference loop to decide
    whether to call W, terminate, or keep generating.
    """
    for s in segs:
        if s.kind in (Kind.TOOL_CALL, Kind.ANSWER):
            return s
    return None
